#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { listThemes, PROJECT_ROOT } from "./theme-core.mjs";

const SAFE_ARTWORK_PATH = /^assets\/theme-art\/[a-z0-9-]+\.(?:svg|png|webp|avif)$/;

function previewMode(mode) {
  const semantic = { ...mode.semantic };
  const compat = Object.fromEntries(
    Object.entries(mode.tokens).filter(([name]) => !name.startsWith("--aura-")),
  );
  return {
    semantic,
    compat,
    // Keep the merged map so the preview applies exactly what the runtime emits.
    tokens: { ...mode.tokens },
    wallpaper: { ...mode.wallpaper },
  };
}

function previewArtwork(artwork, themeName) {
  if (!artwork) return null;
  if (!SAFE_ARTWORK_PATH.test(artwork.path)) {
    throw new Error(`Preview artwork for ${themeName} must be an isolated asset in assets/theme-art`);
  }
  return {
    path: artwork.path,
    position: artwork.position,
    size: artwork.size,
    mobile: artwork.mobile,
  };
}

const themes = await listThemes({ locale: "en" });
const compact = Object.fromEntries(themes.map((theme) => [theme.name, {
  name: theme.name,
  variant: theme.variant,
  label: theme.label,
  description: theme.description,
  labels: { ...theme.labels },
  descriptions: { ...theme.descriptions },
  swatches: [...theme.swatches],
  preview: { ...theme.preview },
  artwork: previewArtwork(theme.artwork, theme.name),
  radius: theme.radius,
  blur: theme.blur,
  typography: { ...theme.typography },
  shape: { ...theme.shape },
  effects: { ...theme.effects },
  light: previewMode(theme.light),
  dark: previewMode(theme.dark),
}]));

// Reference composites under theme_demo_previews are intentionally never read
// or embedded. The harness only points to registry-approved isolated artwork.
const output = `// Generated by scripts/build-preview.mjs.\nwindow.CLAUDE_AURA_THEMES = ${JSON.stringify(compact, null, 2)};\n`;
// The offline QA preview and the Aura Studio share one generated metadata file.
for (const target of [path.join(PROJECT_ROOT, "preview"), path.join(PROJECT_ROOT, "studio")]) {
  const outputPath = path.join(target, "generated-themes.js");
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, output, "utf8");
  console.log(outputPath);
}
